In [1]:
from danilevsky import Danilevski
import numpy as np

## Example

In [2]:
A = np.array([[3, 2, 0, 0, 0], [0, 3, 0, 0, 0], [0, 0, 4, 2, 0], [0, 0, 3, 5, 0], [0, 0, 0, 0, 7]])
eigen_values, eigen_vectors = Danilevski(A)

Vector rieng cua:  7.0
[[0.]
 [0.]
 [0.]
 [0.]
 [1.]]
Vector rieng cua:  2.0
[[ 0.]
 [ 0.]
 [-1.]
 [ 1.]
 [ 0.]]
Vector rieng cua:  7.0
[[0.        ]
 [0.        ]
 [0.66666667]
 [1.        ]
 [0.        ]]
Vector rieng cua:  3.0
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]
Vector rieng cua:  3.0
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [3]:
A = np.array([[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1, 2], [4, 3, 2, 1]])
eigenvalues, eigenvectors = Danilevski(A)

Vector rieng cua:  -3.414213562630226
[[-1.        ]
 [-0.41421356]
 [ 0.41421356]
 [ 1.        ]]
Vector rieng cua:  -1.099019513277647
[[ 1.       ]
 [-1.2198039]
 [-1.2198039]
 [ 1.       ]]
Vector rieng cua:  -0.5857864376269043
[[-1.        ]
 [ 2.41421356]
 [-2.41421356]
 [ 1.        ]]
Vector rieng cua:  9.099019513534778
[[1.       ]
 [0.8198039]
 [0.8198039]
 [1.       ]]
